# Example config file for the Schema Generator
# Use the following command to regenerate entities:
# bin/schema generate-types src/ app/config/schema.yml

types:

  Person:
    parent: false
    properties:
      name: ~
      description: ~
      url: ~
      birthDate: ~
      gender: ~

  BlogPosting:
    parent: false
    properties:
      articleBody: ~
      genre: ~
      url: ~
      author: ~

namespaces:
  entity: AppBundle\Entity

annotationGenerators:
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\PhpDocAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\DoctrineOrmAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\ConstraintAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\ApiPlatformCoreAnnotationGenerator
